### ISSUE TITLE
Flakey results from v0.1.84

### ISSUE THREAD

**Issue by mpollmeier** [ShiftLeftSecurity/fuzzyc2cpg#104]
Since https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/97 was merged (and released as `0.1.84`) we get some flakeyness, at least when used from codepropertygraph.

Steps to reproduce in codepropertygraph: 
* `build.sbt`: `val fuzzyc2cpgVersion = "0.1.84"`
* `sbt semanticcpg/test`

Notes:
* which tests exactly fail seems fairly random
* all versions after .84 are affected

**Comment by fabsx00** [comment]
Reverted for now to investigate.
