### ISSUE TITLE
new/delete keywords don't show up in cpg

### ISSUE THREAD

**Issue by derpsteb** [ShiftLeftSecurity/fuzzyc2cpg#169]
Hey,

I was trying to locate a buffer allocation with the `new` function in a bigger codebase but wasn't able to find it, so I created the following minimal example:

```c++
#include <string.h>
#include <inttypes.h>
int main(){
    uint8_t *buffer = new uint8_t[42];
    delete[] buffer;
}
```
I created the cpg of the given code with `./joern-parse test.cpp`. In Joern I loaded the cpg using `loadCpg("/path/cpg.bin.zip")`. The following queries and their output let me think that the `new` and `delete` keywords are not properly handled at some point. I would assume that the parser recognizes them as they are included in the [grammar](https://github.com/ShiftLeftSecurity/fuzzyc2cpg/blob/d9d577482a8901a59cbd8f27405084d793ed2ce2/src/main/antlr4/io/shiftleft/fuzzyc2cpg/Common.g4#L199). 

```scala
joern> cpg.method.fullName.l 
res6: List[String] = List("main", "<operator>.assignment")

joern> cpg.call.code.l 
res7: List[String] = List("*buffer = new uint8_t[42]")

joern> cpg.call.name(".*assignment").argument.code.l 
res8: List[String] = List("buffer", "42")
```

Am I missing a query to find the allocation I am looking for? Or this just not supported yet?

Thanks!

**Comment by GlassAndOneHalf** [comment]
As discussed privately, `new` and `delete` are not included in the generated CPG. As discussed with @fabsx00 we should try to encode these as CALL nodes.

**Comment by derpsteb** [comment]
This is solved by https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/172. Mind the comment in the PR: Only the class type is saved as argument.
