### ISSUE TITLE
Adapt frontend so that compat passes are no longer required

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/fuzzyc2cpg#178]
Both the `ArgumentCompat` and the `MethodInstCompat(cpg)` pass still need to be run on the output of this frontend, which is quite costly. To increase performance and reduce complexity, let's adapt the frontend such that these two compatibility passes are no longer required.

**Comment by GlassAndOneHalf** [comment]
`ArgumentCompat` should no longer be necessary as I’ve already made the changes in the frontend to support the new Argument edges. I’ll take a look into the `MethodInst` pass though.

**Comment by GlassAndOneHalf** [comment]
Done `MethodInst` removal in https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/179
