### ISSUE TITLE
setup build on travis.ci

### ISSUE THREAD

**Issue by mpollmeier** [ShiftLeftSecurity/fuzzyc2cpg#34]
@davyhua now that this repo is public, the build should be, too. Can you please enable it on travis.ci and configure the following variables just like you did for http://travis-ci.org/ShiftLeftSecurity/codepropertygraph please? i.e.

```
SONATYPE_USERNAME: The email you use to log into https://oss.sonatype.org/
SONATYPE_PASSWORD: The password you use to log into https://oss.sonatype.org/
PGP_PASSPHRASE: <shared on different channel>
GITHUB_TOKEN: the token that allows travis to push to your remote git(hub) repository
```
More context in https://github.com/ShiftLeftSecurity/sbt-ci-release-early#travisci

Once that's done, reassign to me and I'll create the .travis.yml and gpg keys.

**Comment by mpollmeier** [comment]
repo changes should all be in https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/35

@davyhua once you configured the above, feel free to merge the above PR - travis should pick it up and trigger a build

**Comment by davyhua** [comment]
This is done.  https://travis-ci.org/ShiftLeftSecurity/fuzzyc2cpg

**Comment by mpollmeier** [comment]
fyi first green build was https://travis-ci.org/ShiftLeftSecurity/fuzzyc2cpg/jobs/507051215
which published https://oss.sonatype.org/content/repositories/public/io/shiftleft/fuzzyc2cpg_2.12/0.1.5/
which will shortly be on maven central

every push to master will automatically trigger a new release
