### ISSUE TITLE
cpg.method.[internal/external] not implemented

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/fuzzyc2cpg#55]
I noticed that `cpg.method.internal.l` and `cpg.method.external.l` both return `List()` for the code snippet `int main(int argc, char **argv) { }`. It is expected that `cpg.method.internal` contains main, while `cpg.method.external` is empty. `cpg.method.external` should be all methods for which there are outgoing calls only, but no definitions.

**Comment by GlassAndOneHalf** [comment]
In this particular example using the latest FuzzyC2CPG & Joern, `cpg.method.internal.l` contains the main method and the external list is empty. Going to close this as fixed.
