### ISSUE TITLE
Missing TYPE_PARAMETER nodes

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/fuzzyc2cpg#60]
This frontend correctly parses classes with template parameters, but does not create TYPE_PARAMETER nodes and associates them with type declarations via AST edges.

**Comment by GlassAndOneHalf** [comment]
Closing after deciding with @fabsx00 & @ml86 that using the current version of the CPG we wouldn't be able to do anything too useful with the type parameters at this time.
