### ISSUE TITLE
Unable to parse function when if condition contains auto variable type

### ISSUE THREAD

**Issue by hemantabhagat** [ShiftLeftSecurity/fuzzyc2cpg#62]
I have a simple code 

```
static void ToyFunction() {
  if (auto var = GetValue()) {
    // some code
  } else {
    // some code
  }
}
```
the if condition is based on value of variable **var** which is of **auto** type.
Parser fails to parse this function with error 

> Warning: cannot find if for else

there are lots of such errors for any repository.
**Preliminary analysis:**
I checked that, If the type of var changed to any other concrete type like **int** or **bool**, NO error occurs. So there is something has to do with the auto type.

**Comment by GlassAndOneHalf** [comment]
Fixed in #112
